site_name: Guide to the iHop
docs_dir: guide/
extra_css: [extra.css]
pages:
  - Home: index.md
  - Parties:
    - parties/bringing-guests.md
    - parties/being-a-guest.md
  - Living with us:
    - living/guest-manifesto.md
theme: readthedocs
